// <auto-generated />
using System;
using Klases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Klases.Migrations
{
    [DbContext(typeof(Md3Context))]
    [Migration("20251222120432_TestData")]
    partial class TestData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Klases.Assignement", b =>
                {
                    b.Property<int>("AssignementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignementID"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ITSupportID")
                        .HasColumnType("int");

                    b.Property<int?>("TicketID")
                        .HasColumnType("int");

                    b.HasKey("AssignementID");

                    b.HasIndex("ITSupportID");

                    b.HasIndex("TicketID");

                    b.ToTable("Assignements");

                    b.HasData(
                        new
                        {
                            AssignementID = 1,
                            AssignedAt = new DateTime(2025, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comment = "Pārbaudīt printera barošanu.",
                            ITSupportID = 1,
                            TicketID = 1
                        },
                        new
                        {
                            AssignementID = 2,
                            AssignedAt = new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Comment = "Notestēt Excel atjauninājumu.",
                            ITSupportID = 2,
                            TicketID = 2
                        });
                });

            modelBuilder.Entity("Klases.Employee", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("ContractDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            ContractDate = new DateTime(2020, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "anna.ozola@gmail.com",
                            IsActive = true,
                            UserName = "Anna Ozola"
                        },
                        new
                        {
                            UserID = 2,
                            ContractDate = new DateTime(2021, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "janis.berzins@gmail.com",
                            IsActive = true,
                            UserName = "Jānis Bērziņš"
                        });
                });

            modelBuilder.Entity("Klases.ITSupport", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Specialization")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("ITSupports");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "marta.liepa@gmail.com",
                            IsActive = true,
                            Specialization = 2,
                            UserName = "Marta Liepa"
                        },
                        new
                        {
                            UserID = 2,
                            Email = "edgars.kalnins@gmail.com",
                            IsActive = true,
                            Specialization = 1,
                            UserName = "Edgars Kalniņš"
                        });
                });

            modelBuilder.Entity("Klases.Ticket", b =>
                {
                    b.Property<int>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TicketID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketID = 1,
                            Description = "Printeris 2. stāvā neieslēdzas.",
                            EmployeeID = 1,
                            IsResolved = false,
                            Priority = 2,
                            Status = 0,
                            Title = "printeris nestrādā"
                        },
                        new
                        {
                            TicketID = 2,
                            Description = "Excel nereaģē uz peles klikšķiem.",
                            EmployeeID = 2,
                            IsResolved = false,
                            Priority = 3,
                            Status = 1,
                            Title = "Programmas kļūda"
                        });
                });

            modelBuilder.Entity("Klases.Assignement", b =>
                {
                    b.HasOne("Klases.ITSupport", "ITSupport")
                        .WithMany()
                        .HasForeignKey("ITSupportID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Klases.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ITSupport");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Klases.Ticket", b =>
                {
                    b.HasOne("Klases.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID");

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
